// "use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* // add back button */}

      <body
        className={
          inter.className +
          " bg-gray-900 text-white font-inter text-base antialiased"
        }
      >
        
        {children}
      </body>
    </html>
  );
}
